### ISSUE TITLE
error on npm start

### ISSUE THREAD

**Issue by pjirsa** [rackerlabs/canon-bootstrap#79]
[08:11:16] Error: No layout specified for documentation.css
    at convert (d:\development\canon-bootstrap\node_modules\metalsmith-layouts\lib\index.js:112:15)
    at d:\development\canon-bootstrap\node_modules\metalsmith-layouts\node_modules\async\lib\async.js:187:20
    at d:\development\canon-bootstrap\node_modules\metalsmith-layouts\node_modules\async\lib\async.js:239:13
    at _arrayEach (d:\development\canon-bootstrap\node_modules\metalsmith-layouts\node_modules\async\lib\async.js:91:13)
    at _each (d:\development\canon-bootstrap\node_modules\metalsmith-layouts\node_modules\async\lib\async.js:82:13)
    at Object.async.forEachOf.async.eachOf (d:\development\canon-bootstrap\node_modules\metalsmith-layouts\node_modules\async\lib\async.js:238:9)
    at async.forEach.async.each (d:\development\canon-bootstrap\node_modules\metalsmith-layouts\node_modules\async\lib\async.js:215:22)
    at Ware.<anonymous> (d:\development\canon-bootstrap\node_modules\metalsmith-layouts\lib\index.js:135:5)
    at Ware.<anonymous> (d:\development\canon-bootstrap\node_modules\metalsmith\node_modules\ware\node_modules\wrap-fn\index.js:45:19)
    at next (d:\development\canon-bootstrap\node_modules\metalsmith\node_modules\ware\lib\index.js:85:20)
    at d:\development\canon-bootstrap\node_modules\metalsmith\node_modules\ware\node_modules\wrap-fn\index.js:121:18
    at d:\development\canon-bootstrap\node_modules\metalsmith-in-place\node_modules\async\lib\async.js:52:16
    at done (d:\development\canon-bootstrap\node_modules\metalsmith-in-place\node_modules\async\lib\async.js:248:21)
    at d:\development\canon-bootstrap\node_modules\metalsmith-in-place\node_modules\async\lib\async.js:44:16
    at d:\development\canon-bootstrap\node_modules\metalsmith-in-place\lib\index.js:138:9
    at d:\development\canon-bootstrap\node_modules\metalsmith-in-place\node_modules\consolidate\lib\consolidate.js:713:7
    at d:\development\canon-bootstrap\node_modules\metalsmith-in-place\node_modules\consolidate\lib\consolidate.js:146:5
    at tryCatcher (d:\development\canon-bootstrap\node_modules\metalsmith-in-place\node_modules\consolidate\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._resolveFromResolver (d:\development\canon-bootstrap\node_modules\metalsmith-in-place\node_modules\consolidate\node_modules\bluebird\js\main\promise.js:476:31)
    at new Promise (d:\development\canon-bootstrap\node_modules\metalsmith-in-place\node_modules\consolidate\node_modules\bluebird\js\main\promise.js:69:37)
    at promisify (d:\development\canon-bootstrap\node_modules\metalsmith-in-place\node_modules\consolidate\lib\consolidate.js:139:10)
    at exports.handlebars.render (d:\development\canon-bootstrap\node_modules\metalsmith-in-place\node_modules\consolidate\lib\consolidate.js:703:10)

**Comment by mcortez1497** [comment]
Have you performed a fresh `npm install`? 

I haven't seen his error before, but I do find it odd that when I follow the first line of the stack trace (`node_modules\metalsmith-layouts\lib\index.js:112:15`), my `index.js` file in the directory doesn't even have a line 112.

**Comment by davidmginn** [comment]
I'm getting the same error.  Just pulled down the repo this morning and ran npm install.  Deleted everything, cloned and ran npm install again and got the same error.

**Comment by eddywashere** [comment]
There were a lot of changes in the 1.x.x version. https://github.com/superwolff/metalsmith-layouts/blob/master/History.md

Might be worth pinning dependencies with tilde style instead of caret style: `~1.3.X`.

**Comment by mcortez1497** [comment]
@eddywashere Yea, that's the issue. Setting the version of `metalsmith-layouts` to `~1.2.1` and installing seems to solve the issue. I'll make a PR.
